const Types = {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  SHOW_THEME_VIEW: 'SHOW_THEME_VIEW',
  POPULAR_REFRESH: 'POPULAR_REFRESH',
  POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL',
  POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS',
  POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS',
  POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL',
  TAGNAME_LOAD_SUCCESS: 'TAGNAME_LOAD_SUCCESS',
};

export default Types;
