require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '13.4'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'GitHub_RN' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true,  # Hermes 启用配置
    :fabric_enabled => false  # 如果你不需要 Fabric，可以禁用
  )

  # 添加其他 Pods
  # pod 'RNScreens', :path => '../node_modules/react-native-screens'
  # pod 'react-native-async-storage', :path => '../node_modules/@react-native-async-storage/async-storage'
  # pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'GitHub_RNTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
      end
    end

    # react_native_post_install 调用
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
      # :ccache_enabled => true
    )
  end
end
